ci:
  autoupdate_commit_msg: "chore: update pre-commit hooks"
  autoupdate_schedule: weekly
  autofix_commit_msg: "style: pre-commit fixes"

repos:
  - repo: https://github.com/psf/black-pre-commit-mirror
    rev: "23.1.0"
    hooks:
      - id: black
        args:
          - "--preview"

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: check-symlinks
      - id: check-yaml
      - id: debug-statements
      - id: end-of-file-fixer
      - id: mixed-line-ending
      - id: requirements-txt-fixer
      - id: trailing-whitespace

  - repo: https://github.com/tox-dev/pyproject-fmt
    rev: "0.7.0"
    hooks:
      - id: pyproject-fmt

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.0.255
    hooks:
      - id: ruff
        args: ["--fix", "--show-fixes"]

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.0.1
    hooks:
      - id: mypy
        files: ^nox/
        args: []
        additional_dependencies:
          - jinja2
          - packaging
          - importlib_metadata

  - repo: https://github.com/codespell-project/codespell
    rev: v2.2.2
    hooks:
      - id: codespell

  - repo: https://github.com/pre-commit/pygrep-hooks
    rev: v1.10.0
    hooks:
      - id: python-no-eval
        exclude: ^nox/manifest.py$
      - id: rst-backticks
      - id: rst-directive-colons
      - id: rst-inline-touching-normal
