language: python
matrix:
  include:
  - python: '3.5'
    env: NOXSESSION="tests-3.5"
  - python: '3.6'
    env: NOXSESSION="tests-3.6"
  - python: '3.7'
    env: NOXSESSION="tests-3.7"
    dist: xenial    # required for Python 3.7 (travis-ci/travis-ci#9069)
  - python: '3.7'
    env: NOXSESSION="lint"
    dist: xenial    # required for Python 3.7 (travis-ci/travis-ci#9069)
  - python: '3.7'
    env: NOXSESSION="docs"
    dist: xenial    # required for Python 3.7 (travis-ci/travis-ci#9069)
before_install:
  # Only test with conda on one test session.
  - if [ ${NOXSESSION} == "tests-3.7" ] then
      wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
      chmod +x miniconda.sh
      ./miniconda.sh -b
      # Prefer the built-in python binary.
      export PATH="$PATH:/home/travis/miniconda/bin"
      conda update --yes conda
    fi
install:
  - pip install --upgrade pip setuptools
  - pip install .
script: nox --non-interactive --session "$NOXSESSION"
deploy:
  provider: pypi
  user: theacodes
  password:
    secure: ETRTnYg+8cilT0/HidhyPljERgE/u0boKdH9TW+JrY0De40Km5C+TUmPagKJuwPx1Gw8HNN1vN7M1pqaQ/flQaY9iNbuJZr5ZaApiZW1pw5/nO2wWoANx0hiChdjvwbJZdqUFEoba6MS9aBY7TroFlLjW6dUg8MZFSiUFRQDF9rTCyzB/juC7wiLTgrjlFpOvaOmf1qpVOajY5kfn8MLELms8itRUa04X4kqqgtOfifoA1CevObrScGSXlpPtqmoxUrCmwbnHu9qnqgAWLHe3y7fI4ZqscYQv/JCW8NdJgqMTn0jctLXibHt5vC/DtUYo47mFSRBfn55ZwAFiV6IiwVbtDKby0ZdNO2uIFn4B/7l0qrLTwnZbRy4vkPqEeJoS75vl4JQrauGmI+hgdtesHjZxLzs94H4vINVt0fGpkYqbgtMQO8HUQnnj0FJXcGKo4A5OuLjnk5+rgTSvLT/5qNg/cyve5BXkn1ib6ecah21MHSQyhl5CxIFBH6S6BRrGoxXluLqXPVv/w+QA0lxXCpAPfbHuMt4r9522YN/XfGQNHfNqK/836UbLEX5ZXZiZLl01IvVPl+3eC/Qmpc+tNXb51d53Qsm89VtaNGGvuV2eLPBR+gfXcQ8wFB1HW3Q3oshHCGW4KKApyzyYKWq27JPlGV13Yh+NMHWs9PGHyI=
  on:
    tags: true
    distributions: sdist bdist_wheel
    repo: theacodes/nox
    condition: "$NOXSESSION = \"tests-3.6\""
